spring:
  profiles:
    active: docker

  application:
    name: employee-management

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  cache:
    type: redis
    redis:
      cache-null-values: true

logging:
  level:
    org:
      springframework:
        data:
          redis: DEBUG
        cache: DEBUG

server:
  port: 8088