spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/employee_management_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cache:
    type: redis
    redis:
      cache-null-values: true

  redis:
    host: redisdb
    port: 6379

server:
  port: 8088